# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\"\x13\n\x11\x43SQueryCharacters\"\xc5\x01\n\nDCharacter\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nprofession\x18\x03 \x01(\x05\x12\r\n\x05level\x18\x04 \x01(\x05\x12\x0b\n\x03sex\x18\x05 \x01(\x05\x12\r\n\x05model\x18\x06 \x01(\t\x12\x14\n\x0csurvive_time\x18\x07 \x01(\x03\x12\x14\n\x0c\x65quipWeapon1\x18\x08 \x01(\x05\x12\x14\n\x0c\x65quipWeapon2\x18\t \x01(\x05\x12\x10\n\x08vipLevel\x18\n \x01(\x05\x12\n\n\x02sn\x18\x0b \x01(\x05\":\n\x17SCQueryCharactersResult\x12\x1f\n\ncharacters\x18\x01 \x03(\x0b\x32\x0b.DCharacter\"6\n\x11\x43SCharacterCreate\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0bkeyActivate\x18\x02 \x01(\t\"a\n\x17SCCharacterCreateResult\x12\x12\n\nresultCode\x18\x01 \x02(\x05\x12\x14\n\x0cresultReason\x18\x02 \x01(\t\x12\x0f\n\x07humanId\x18\x03 \x01(\x03\x12\x0b\n\x03url\x18\x04 \x01(\t\"\x1f\n\x11\x43SCharacterDelete\x12\n\n\x02id\x18\x01 \x02(\x03\"O\n\x17SCCharacterDeleteResult\x12\x12\n\nresultCode\x18\x01 \x02(\x05\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x14\n\x0csurvive_time\x18\x03 \x01(\x03\"#\n\x10\x43SCharacterLogin\x12\x0f\n\x07humanId\x18\x01 \x02(\x03\"L\n\x16SCCharacterLoginResult\x12\x12\n\nresultCode\x18\x01 \x02(\x05\x12\x1e\n\tloginType\x18\x02 \x01(\x0e\x32\x0b.ELoginType\"%\n\x17\x43SCharacterCancelDelete\x12\n\n\x02id\x18\x01 \x02(\x03\"?\n\x1dSCCharacterCancelDeleteResult\x12\x12\n\nresultCode\x18\x01 \x02(\x05\x12\n\n\x02id\x18\x02 \x01(\x03\"\x11\n\x0f\x43SCharacterExit*\\\n\nELoginType\x12\x11\n\rLOGIN_DEFAULT\x10\x00\x12\x13\n\x0f\x44\x41Y_FIRST_LOGIN\x10\x01\x12\x11\n\rRECOVER_LOGIN\x10\x02\x12\x13\n\x0f\x44\x41Y_MULTI_LOGIN\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ELOGINTYPE._serialized_start=803
  _ELOGINTYPE._serialized_end=895
  _CSQUERYCHARACTERS._serialized_start=15
  _CSQUERYCHARACTERS._serialized_end=34
  _DCHARACTER._serialized_start=37
  _DCHARACTER._serialized_end=234
  _SCQUERYCHARACTERSRESULT._serialized_start=236
  _SCQUERYCHARACTERSRESULT._serialized_end=294
  _CSCHARACTERCREATE._serialized_start=296
  _CSCHARACTERCREATE._serialized_end=350
  _SCCHARACTERCREATERESULT._serialized_start=352
  _SCCHARACTERCREATERESULT._serialized_end=449
  _CSCHARACTERDELETE._serialized_start=451
  _CSCHARACTERDELETE._serialized_end=482
  _SCCHARACTERDELETERESULT._serialized_start=484
  _SCCHARACTERDELETERESULT._serialized_end=563
  _CSCHARACTERLOGIN._serialized_start=565
  _CSCHARACTERLOGIN._serialized_end=600
  _SCCHARACTERLOGINRESULT._serialized_start=602
  _SCCHARACTERLOGINRESULT._serialized_end=678
  _CSCHARACTERCANCELDELETE._serialized_start=680
  _CSCHARACTERCANCELDELETE._serialized_end=717
  _SCCHARACTERCANCELDELETERESULT._serialized_start=719
  _SCCHARACTERCANCELDELETERESULT._serialized_end=782
  _CSCHARACTEREXIT._serialized_start=784
  _CSCHARACTEREXIT._serialized_end=801
# @@protoc_insertion_point(module_scope)
