# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\x12\x18\x63om.sirius.bootstrap.msg\"Q\n\x07Message\x12=\n\x0bmoveMessage\x18\xe9\x07 \x01(\x0b\x32%.com.sirius.bootstrap.msg.MoveMessageH\x00\x42\x07\n\x05msgId\"s\n\x0bMoveMessage\x12\x10\n\x08playerId\x18\x01 \x01(\t\x12\x0c\n\x04posX\x18\x02 \x01(\x02\x12\x0c\n\x04posY\x18\x03 \x01(\x02\x12\x0c\n\x04posZ\x18\x04 \x01(\x02\x12\x0c\n\x04rotX\x18\x05 \x01(\x02\x12\x0c\n\x04rotY\x18\x06 \x01(\x02\x12\x0c\n\x04rotZ\x18\x07 \x01(\x02\"\xbc\x01\n\x0bPlayerState\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x12\n\nposition_x\x18\x02 \x01(\x02\x12\x12\n\nposition_y\x18\x03 \x01(\x02\x12\x12\n\nposition_z\x18\x04 \x01(\x02\x12\x12\n\nrotation_y\x18\x05 \x01(\x02\x12\r\n\x05speed\x18\x06 \x01(\x02\x12\x12\n\nis_jumping\x18\x07 \x01(\x08\x12\x14\n\x0cis_sprinting\x18\x08 \x01(\x08\x12\x11\n\ttimestamp\x18\t \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=39
  _MESSAGE._serialized_end=120
  _MOVEMESSAGE._serialized_start=122
  _MOVEMESSAGE._serialized_end=237
  _PLAYERSTATE._serialized_start=240
  _PLAYERSTATE._serialized_end=428
# @@protoc_insertion_point(module_scope)
